WebSrv/Controllers/ServerController.cs
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
//
using WebSrv.Models;
using NSG.Identity;
using NSG.Identity.Incidents;
using NSG.Library.Logger;
using System.Data.Entity.Validation;
//
namespace WebSrv.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ServerController : BaseController
    {
        ApplicationDbContext _content;
        ServerStore _serverStore;
        CompanyServerAccess _companyServerAccess;
        //
        /// <summary>
        /// No parameter constructor
        /// </summary>
        public ServerController() :base()
        {
            _content = ApplicationDbContext.Create();
            _serverStore = new ServerStore(_content);
            _companyServerAccess = new CompanyServerAccess(_content);
        }
        //
        /// <summary>
        /// Inject the context, 1 parameter constructor
        /// </summary>
        public ServerController(ApplicationDbContext content) : base()
        {
            _content = content;
            _serverStore = new ServerStore(_content);
        }
        //
        /// <summary>
        /// GET: Server
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View(_content.Companies);
        }
        //
        // GET: Server/Details/5
        public ActionResult Details(int id)
        {
            CompanyServerAccess _csa = new CompanyServerAccess(_content);
            return View(_csa.GetById(id));
        }
        //
        // -------------------------------------------------------------------
        // Create
        //
        /// <summary>
        /// GET: Server/Create
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            return View();
        }
        //
        /// <summary>
        /// POST: Server/Create
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CompanyCreate( CompanyServerData model )
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _companyServerAccess.CompanyInsert( model );
                    return RedirectToAction("Edit", new { id = model.CompanyId });
                }
                else
                    Base_AddErrors(ModelState);
            }
            catch (DbEntityValidationException _entityEx)
            {
                // extension method
                string _errors = _entityEx.EntityValidationErrors.GetDbValidationErrors();
                Log.Logger.Log(LoggingLevel.Error, User.Identity.Name, MethodBase.GetCurrentMethod(), _errors, _entityEx);
                Base_AddErrors(_entityEx);
            }
            catch ( Exception _ex )
            {
                Log.Logger.Log(LoggingLevel.Error, User.Identity.Name, MethodBase.GetCurrentMethod(), _ex.Message, _ex);
                Base_AddErrors(_ex);
            }
            return RedirectToAction("Create");
        }
        //
        /// <summary>
        /// POST: Server/Edit/5
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ServerCreate(ServerData model)
        {
            try
            {
                int _companyId = model.CompanyId;
                if (ModelState.IsValid)
                {
                    if( model.DST && model.DST_Start != null && model.DST_End != null )
                        _companyServerAccess.ServerInsert(model);
                    else
                        Error( "DTS requires start/end dates." );
                }
                else
                    Base_AddErrors(ModelState);
                return RedirectToAction("Edit", new { id = _companyId });
            }
            catch (DbEntityValidationException _entityEx)
            {
                // extension method
                string _errors = _entityEx.EntityValidationErrors.GetDbValidationErrors();
                Log.Logger.Log(LoggingLevel.Error, User.Identity.Name, MethodBase.GetCurrentMethod(), _errors, _entityEx);
                Base_AddErrors(_entityEx);
            }
            catch (Exception _ex)
            {
                Log.Logger.Log(LoggingLevel.Error, User.Identity.Name, MethodBase.GetCurrentMethod(), _ex.Message, _ex);
                Base_AddErrors(_ex);
            }
            return RedirectToAction("Index");
        }
        //
        // -------------------------------------------------------------------
        // Edit
        //
        /// <summary>
        /// GET: Server/Edit/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(int id)
        {
            return View(_companyServerAccess.GetById(id));
        }
        //
        /// <summary>
        /// POST: Server/Edit/5
        /// </summary>
        /// <param name="id"></param>
        /// <param name="collection"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CompanyEdit(int id, CompanyServerData model )
        {
            try
            {
                if ( ModelState.IsValid )
                {
                    int ret = _companyServerAccess.CompanyUpdate( model );
                }
                else
                    Base_AddErrors( ModelState );
                return RedirectToAction("Edit", new { id = model.CompanyId });
            }
            catch (DbEntityValidationException _entityEx)
            {
                string _errors = _entityEx.EntityValidationErrors.GetDbValidationErrors();
                Log.Logger.Log(LoggingLevel.Error, User.Identity.Name, MethodBase.GetCurrentMethod(), _errors, _entityEx);
                Base_AddErrors(_entityEx);
            }
            catch (Exception _ex)
            {
                Log.Logger.Log(LoggingLevel.Error, User.Identity.Name, MethodBase.GetCurrentMethod(), _ex.Message, _ex);
                Base_AddErrors(_ex);
            }
            return View();
        }
        //
        /// <summary>
        /// POST: Server/Edit/5
        /// </summary>
        /// <param name="id"></param>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ServerEdit(int id, ServerData model)
        {
            try
            {
                int _companyId = model.CompanyId;
                if (ModelState.IsValid)
                {
                    if ( model.DST && model.DST_Start != null && model.DST_End != null )
                        _companyServerAccess.ServerUpdate( model );
                    else
                        Error( "DTS requires start/end dates." );
                }
                else
                    Base_AddErrors(ModelState);
                return RedirectToAction("Edit", new { id = _companyId } );
            }
            catch (DbEntityValidationException _entityEx)
            {
                // extension method
                string _errors = _entityEx.EntityValidationErrors.GetDbValidationErrors();
                Log.Logger.Log(LoggingLevel.Error, User.Identity.Name, MethodBase.GetCurrentMethod(), _errors, _entityEx);
                Base_AddErrors(_entityEx);
            }
            catch ( Exception _ex )
            {
                Log.Logger.Log(LoggingLevel.Error, User.Identity.Name, MethodBase.GetCurrentMethod(), _ex.Message, _ex);
                Base_AddErrors(_ex);
            }
            return RedirectToAction("Index");
        }
        //
        // -------------------------------------------------------------------
        // Delete of company and servers
        //
        /// <summary>
        /// GET: Server/Delete/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Delete(int id)
        {
            return View(_companyServerAccess.GetById(id));
        }
        //
        /// <summary>
        /// POST: Server/CompanyDelete/5
        /// </summary>
        /// <param name="id"></param>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CompanyDelete(int id, CompanyServerData model )
        {
            try
            {
                _companyServerAccess.CompanyDelete(id);
                return RedirectToAction("Index");
            }
            catch (DbEntityValidationException _entityEx)
            {
                string _errors = _entityEx.EntityValidationErrors.GetDbValidationErrors();
                Log.Logger.Log(LoggingLevel.Error, User.Identity.Name, MethodBase.GetCurrentMethod(), _errors, _entityEx);
                Base_AddErrors(_entityEx);
            }
            catch (Exception _ex)
            {
                Log.Logger.Log(LoggingLevel.Error, User.Identity.Name, MethodBase.GetCurrentMethod(), _ex.Message, _ex);
                Base_AddErrors(_ex);
            }
            return RedirectToAction("Delete", new { id = id });
        }
        //
        /// <summary>
        /// POST: Server/ServerDelete/5
        /// </summary>
        /// <param name="id"></param>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ServerDelete(int id, CompanyServerData model)
        {
            int _companyId = model.CompanyId;
            try
            {
                _companyServerAccess.ServerDelete(id);
                return RedirectToAction("Delete", new { id = _companyId });
            }
            catch (DbEntityValidationException _entityEx)
            {
                string _errors = _entityEx.EntityValidationErrors.GetDbValidationErrors();

WebSrv/Views/Server/Create.cshtml
@model WebSrv.Models.CompanyServerData
@{
    ViewBag.Title = "Create";
}
<h2>Company/Server (Create)</h2>
<hr />
@using (Html.BeginForm("CompanyCreate", "Server", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-actions no-color">
        <div class="nsg-float-left text-left">
            <span>
                @Html.ActionLink("Back to List", "Index")
            </span>
        </div>
        <div class="nsg-float-right text-right">
            <span>
                <input type="submit" value="Create" class="btn btn-info" />
            </span>
        </div>
        <div style="clear: both;"></div>
    </div>
    <div class="form-horizontal">
        <div class="form-group">
            <label class="col-lg-1 col-md-2 col-sm-12 nsg-label" for="ServerId">Id</label>
            <div class="col-lg-1 col-md-1 col-sm-120">
                @Html.DisplayFor(model => model.CompanyId)
            </div>
        </div>
        <div class="form-group">
            <label class="col-lg-1 col-md-2 col-sm-12 nsg-label" for="CompanyShortName">Short Name</label>
            <div class="col-lg-1 col-md-1 col-sm-120">
                @Html.EditorFor(model => model.CompanyShortName, new { htmlAttributes = new { @class = "form-control", @maxlength = "12", @style = "width:160px" } })
                @Html.ValidationMessageFor(model => model.CompanyShortName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-lg-1 col-md-2 col-sm-12 nsg-label" for="CompanyName">Name</label>
            <div class="col-lg-1 col-md-1 col-sm-120">
                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control", @maxlength = "80", @style = "max-width:680px" } })
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="nsg-clear-left"></div>
}

WebSrv/Views/Server/Delete.cshtml
@model WebSrv.Models.CompanyServerData
@{
    ViewBag.Title = "Delete";
}
<h2>Company/Server (Delete)</h2>
<div>
    <hr />
    @using (Html.BeginForm("CompanyDelete", "Server", new { id = @Model.CompanyId }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <div class="nsg-float-left text-left">
                <span>
                    @Html.ActionLink("Back to List", "Index")
                </span>
            </div>
            <div class="nsg-float-right text-right">
                <span>
                    <strong>Are you sure you want to delete this Company?</strong>
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </span>
            </div>
            <div class="nsg-clear-both"></div>
        </div>
        @Html.HiddenFor(model => model.CompanyId)
        @Html.HiddenFor(model => model.CompanyShortName)
        @Html.HiddenFor(model => model.CompanyName)
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.CompanyId):
            </dt>
            <dd>
                @Html.DisplayFor(model => model.CompanyId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CompanyShortName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.CompanyShortName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CompanyName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.CompanyName)
            </dd>
        </dl>
    }

    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        @if (Model != null)
        {
            foreach (var srv in Model.Servers)
            {
                using (Html.BeginForm("ServerDelete", "Server", new { id = srv.ServerId }, FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.CompanyId)
                    @Html.HiddenFor(model => model.CompanyShortName)
                    @Html.HiddenFor(model => model.CompanyName)
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="@string.Format("panel-{0}", srv.ServerId)">
                            <div class="panel-title">
                                <a class="collapsed accordion-toggle" role="button" data-toggle="collapse"
                                   data-parent="#accordion"
                                   href="@string.Format("#collapse-{0}", srv.ServerId)"
                                   aria-expanded="false" aria-controls="@string.Format("collapse-{0}", srv.ServerId)">
                                    <label class="col-lg-1 col-md-1 col-sm-12 nsg-label" for="ServerShortName">Server:</label>
                                    <div class="col-lg-1 col-md-1 col-sm-121">
                                        @Html.DisplayFor(model => srv.ServerShortName)
                                        (@Html.DisplayFor(model => srv.ServerId))
                                        - @Html.DisplayFor(model => srv.ServerName)
                                    </div>
                                    <div class="nsg-clear-left"></div>
                                </a>
                            </div>
                        </div>
                        <div id="@string.Format("collapse-{0}", srv.ServerId)" class="panel-collapse collapse" role="tabpanel" aria-labelledby="@string.Format("panel-{0}", srv.ServerId)">
                            <div class="panel-body">
                                <div class="col-lg-1 col-md-1 col-sm-121">
                                </div>
                                <div class="col-lg-1 col-md-1 col-sm-12">
                                    <input type="submit" value="Delete" class="btn btn-danger" />
                                </div>
                                @Html.Partial("ServerDetailPartial", srv)
                            </div>
                        </div>
                    </div>
                }
            }
        }
    </div>
</div>

WebSrv/Views/Server/Details.cshtml
@model WebSrv.Models.CompanyServerData
@{
    ViewBag.Title = "Details";
}
<h2>Company/Server (Details)</h2>
<hr />
<div>
    <div class="form-actions no-color">
        <div class="nsg-float-left text-left">
            <span>
                @Html.ActionLink("Back to List", "Index")
            </span>
        </div>
        <div class="nsg-float-right text-right">
            <span>
                @Html.ActionLink("Edit", "Edit", new { id = Model.CompanyId })
            </span>
        </div>
        <div class="nsg-clear-both"></div>
    </div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyId):
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CompanyId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyShortName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CompanyShortName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyName):
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>
    </dl>
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        @if (Model != null)
        {
            foreach (var srv in Model.Servers)
            {
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="@string.Format("panel-{0}", srv.ServerId)">
                        <div class="panel-title">
                            <a class="collapsed accordion-toggle" role="button" data-toggle="collapse"
                               data-parent="#accordion"
                               href="@string.Format("#collapse-{0}", srv.ServerId)"
                               aria-expanded="false" aria-controls="@string.Format("collapse-{0}", srv.ServerId)">
                                <label class="col-lg-1 col-md-1 col-sm-12 nsg-label" for="ServerShortName">Server:</label>
                                <div class="col-lg-1 col-md-1 col-sm-121">
                                    @Html.DisplayFor(model => srv.ServerShortName)
                                    (@Html.DisplayFor(model => srv.ServerId))
                                    - @Html.DisplayFor(model => srv.ServerName)
                                </div>
                                <div class="nsg-clear-left"></div>
                            </a>
                        </div>
                    </div>
                    <div id="@string.Format("collapse-{0}", srv.ServerId)" class="panel-collapse collapse" role="tabpanel" aria-labelledby="@string.Format("panel-{0}", srv.ServerId)">
                        <div class="panel-body">
                            @Html.Partial("ServerDetailPartial", srv)
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>

WebSrv/Views/Server/Edit.cshtml
@model WebSrv.Models.CompanyServerData
@{
    ViewBag.Title = "Company/Server Edit";
    // create the server-create-partial w/ pre-initialized values from 1st row
    WebSrv.Models.ServerData createServer = new WebSrv.Models.ServerData();
    createServer.CompanyId = Model.CompanyId;
    createServer.CompanyName = Model.CompanyName;
    if (Model != null)
    {
        if (Model.Servers != null)
        {
            if (Model.Servers.Count > 0)
            {
                WebSrv.Models.ServerData server = Model.Servers[0];
                createServer.ServerLocation = server.ServerLocation;
                createServer.FromName = server.FromName;
                createServer.FromNicName = server.FromNicName;
                createServer.FromEmailAddress = server.FromEmailAddress;
                createServer.TimeZone = server.TimeZone;
                createServer.DST = server.DST;
                createServer.TimeZone_DST = server.TimeZone_DST;
                createServer.DST_Start = server.DST_Start;
                createServer.DST_End = server.DST_End;
            }
        }
    }
}
<h2>Company/Server (Edit)</h2>
<hr />
@using (Html.BeginForm("CompanyEdit", "Server", new { id = @Model.CompanyId }, FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-actions no-color">
        <div class="nsg-float-left text-left">
            <span>
                @Html.ActionLink("Back to List", "Index")
            </span>
        </div>
        <div class="nsg-float-right text-right">
            <span>
                <input type="submit" value="Save" class="btn btn-info" />
            </span>
        </div>
        <div style="clear: both;"></div>
    </div>
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CompanyId)
        <div class="form-group">
            <label class="col-lg-1 col-md-2 col-sm-12 nsg-label" for="ServerId">Id</label>
            <div class="col-lg-1 col-md-1 col-sm-120">
                @Html.DisplayFor(model => model.CompanyId)
            </div>
        </div>
        <div class="form-group">
            <label class="col-lg-1 col-md-2 col-sm-12 nsg-label" for="CompanyShortName">Short Name</label>
            <div class="col-lg-1 col-md-1 col-sm-120">
                @Html.EditorFor(model => model.CompanyShortName, new { htmlAttributes = new { @class = "form-control", @maxlength = "12", @style = "width:160px" } })
                @Html.ValidationMessageFor(model => model.CompanyShortName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-lg-1 col-md-2 col-sm-12 nsg-label" for="CompanyName">Name</label>
            <div class="col-lg-1 col-md-1 col-sm-120">
                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control", @maxlength = "80", @style = "max-width:680px" } })
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="nsg-clear-left"></div>
}
<div>
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="panel-new">
                <div class="panel-title">
                    <a class="collapsed accordion-toggle" role="button" data-toggle="collapse"
                       data-parent="#accordion"
                       href="#collapse-new"
                       aria-expanded="false" aria-controls="collapse-new">
                        <div class="nsg-bold col-lg-1 col-md-1 col-sm-12">
                            Add Server
                        </div>
                        <div class="nsg-clear-left"></div>
                    </a>
                </div>
            </div>
            <div id="collapse-new" class="panel-collapse collapse" role="tabpanel" aria-labelledby="panel-new">
                <div class="panel-body">
                    @Html.Partial("ServerCreatePartial", createServer)
                </div>
            </div>
        </div>
        @if ( Model != null )
        {
            foreach (var srv in Model.Servers)
            {
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="@string.Format("panel-{0}",srv.ServerId)">
                        <div class="panel-title">
                            <a class="collapsed accordion-toggle" role="button" data-toggle="collapse"
                               data-parent="#accordion"
                               href="@string.Format("#collapse-{0}",srv.ServerId)"
                               aria-expanded="false" aria-controls="@string.Format("collapse-{0}",srv.ServerId)">
                                <label class="col-lg-1 col-md-1 col-sm-12 nsg-label" for="ServerShortName">Edit:</label>
                                <div class="col-lg-1 col-md-1 col-sm-121">
                                    @Html.DisplayFor(model => srv.ServerShortName)
                                    (@Html.DisplayFor(model => srv.ServerId))
                                    - @Html.DisplayFor(model => srv.ServerName)
                                </div>
                                <div class="nsg-clear-left"></div>
                            </a>
                        </div>
                    </div>
                    <div id="@string.Format("collapse-{0}",srv.ServerId)" class="panel-collapse collapse" role="tabpanel" aria-labelledby="@string.Format("panel-{0}",srv.ServerId)">
                        <div class="panel-body">
                            @Html.Partial("ServerEditPartial", srv)
                        </div>
                    </div>
                </div>
            }
        }
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="panel-help">
                <div class="panel-title">
                    <a class="collapsed accordion-toggle" role="button" data-toggle="collapse"
                       data-parent="#accordion"
                       href="#collapse-help"
                       aria-expanded="false" aria-controls="collapse-help">
                        <div class="nsg-bold col-lg-1 col-md-1 col-sm-12">
                            E-Mail Template Variable List
                        </div>
                        <div class="nsg-clear-left"></div>
                    </a>
                </div>
            </div>
            <div id="collapse-help" class="panel-collapse collapse" role="tabpanel" aria-labelledby="panel-help">
                <div class="panel-body">
                    @Html.Partial("../Shared/EmailTemplateHelpPartial")
                </div>
            </div>
        </div>
    </div>
</div>

WebSrv/Views/Server/Index.cshtml
@model IEnumerable<NSG.Identity.Incidents.Company>
@{
    ViewBag.Title = "Index";
}
<h2>Companies/Servers Management</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.CompanyName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td style="width: 120px;">
            @Html.ActionLink("Details", "Details", new { id = item.CompanyId }) |
            @Html.ActionLink("Edit", "Edit", new { id = item.CompanyId })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CompanyName)
            ( @Html.DisplayFor(modelItem => item.CompanyId)
            - @Html.DisplayFor(modelItem => item.CompanyShortName) )
        </td>
        <td>
            @Html.ActionLink("Delete", "Delete", new { id=item.CompanyId }, new { @style = "color: red;" })
        </td>
    </tr>
    <tr>
        <td colspan="3" style="border-top: none;">
            <div class="nsg-label" style="width: 120px; float: left; padding-right: 15px;">
                Servers:
            </div>
            @foreach (var srv in item.Servers)
            {
                <div style="width: 100px; float: left;">
                    @Html.ActionLink(srv.ServerShortName, "Edit", new { id = item.CompanyId })
                </div>
            }
            <div style="clear: left;"></div>
        </td>
    </tr>
}

</table>

WebSrv/Views/Server/ServerTemplateHelpPartial.cshtml
<div class="form-horizontal">
    <div class="nsg-container">
        <label for="IncidentId" class="col-lg-2 col-md-3 col-sm-12 nsg-label">IncidentId</label>
        <div id="IncidentId" class="col-lg-4 col-md-5 col-sm-12">'Id' from Incident</div>
    </div>
    <div class="nsg-container">
        <label for="AbuseEmailAddress" class="col-lg-2 col-md-3 col-sm-12 nsg-label">AbuseEmailAddress</label>
        <div id="AbuseEmailAddress" class="col-lg-4 col-md-5 col-sm-12">'Abuse Email' from Incident</div>
    </div>
    <div class="nsg-container">
        <label for="IPAddress" class="col-lg-2 col-md-3 col-sm-12 nsg-label">IPAddress</label>
        <div id="IPAddress" class="col-lg-4 col-md-5 col-sm-12">'IP Address' from Incident</div>
    </div>
    <div class="nsg-container">
        <label for="IncidentTypeShortDesc" class="col-lg-2 col-md-3 col-sm-12 nsg-label">IncidentTypeShortDesc</label>
        <div id="IncidentTypeShortDesc" class="col-lg-4 col-md-5 col-sm-12">'Incident Type Short Description' from Template</div>
    </div>
    <div class="nsg-container">
        <label for="IncidentTypeDesc" class="col-lg-2 col-md-3 col-sm-12 nsg-label">IncidentTypeDesc</label>
        <div id="IncidentTypeDesc" class="col-lg-4 col-md-5 col-sm-12">'Incident Type Description' from Template</div>
    </div>
    <div class="nsg-container">
        <label for="UserName" class="col-lg-2 col-md-3 col-sm-12 nsg-label">UserName</label>
        <div id="UserName" class="col-lg-4 col-md-5 col-sm-12">'User Name' from User</div>
    </div>
    <div class="nsg-container">
        <label for="UserNicName" class="col-lg-2 col-md-3 col-sm-12 nsg-label">UserNicName</label>
        <div id="UserNicName" class="col-lg-4 col-md-5 col-sm-12">'User Nic Name' from User</div>
    </div>
    <div class="nsg-container">
        <label for="UserEmailAddress" class="col-lg-2 col-md-3 col-sm-12 nsg-label">UserEmailAddress</label>
        <div id="UserEmailAddress" class="col-lg-4 col-md-5 col-sm-12">'Email Address' from User</div>
    </div>
    <div class="nsg-container">
        <label for="ServerDescription" class="col-lg-2 col-md-3 col-sm-12 nsg-label">ServerDescription</label>
        <div id="ServerDescription" class="col-lg-4 col-md-5 col-sm-12">'Server Description' from Server</div>
    </div>
    <div class="nsg-container">
        <label for="Device" class="col-lg-2 col-md-3 col-sm-12 nsg-label">Device</label>
        <div id="Device" class="col-lg-4 col-md-5 col-sm-12">'Device' from Server</div>
    </div>
    <div class="nsg-container">
        <label for="ServerLocation" class="col-lg-2 col-md-3 col-sm-12 nsg-label">ServerLocation</label>
        <div id="ServerLocation" class="col-lg-4 col-md-5 col-sm-12">'Server Location' from Server</div>
    </div>
    <div class="nsg-container">
        <label for="FromName" class="col-lg-2 col-md-3 col-sm-12 nsg-label">FromName</label>
        <div id="FromName" class="col-lg-4 col-md-5 col-sm-12">'From Name' from Server</div>
    </div>
    <div class="nsg-container">
        <label for="FromNicName" class="col-lg-2 col-md-3 col-sm-12 nsg-label">FromNicName</label>
        <div id="FromNicName" class="col-lg-4 col-md-5 col-sm-12">'From Nic Name' from Server</div>
    </div>
    <div class="nsg-container">
        <label for="FromEmailAddress" class="col-lg-2 col-md-3 col-sm-12 nsg-label">FromEmailAddress</label>
        <div id="FromEmailAddress" class="col-lg-4 col-md-5 col-sm-12">'From Email Address' from Server</div>
    </div>
</div>