WebSrv/Controllers/UsersAdminController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security.DataProtection;
//
using NSG.Identity;
using NSG.Identity.Api;
using NSG.Identity.Models;
using NSG.Identity.Incidents;
using NSG.Identity.Providers;
//
namespace WebSrv.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersAdminController : BaseController
    {
        public UsersAdminController() : base()
        {
        }
        //
        public UsersAdminController(ApplicationUserManager userManager,
            ApplicationRoleManager roleManager) : base()
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }
        //
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }
        private ApplicationServerManager _serverManager;
        public ApplicationServerManager ServerManager
        {
            get
            {
                return _serverManager ?? Request.GetOwinContext().Get<ApplicationServerManager>();
            }
            private set { _serverManager = value; }
        }
        //
        /// <summary>
        /// GET: /Users/
        /// </summary>
        /// <returns>View of a list of users</returns>
        public async Task<ActionResult> Index()
        {
            return View(await UserManager.Users.ToListAsync());
        }
        //
        /// <summary>
        /// GET: /Users/Details/5
        /// </summary>
        /// <param name="id">guid of a user</param>
        /// <returns>a single application user</returns>
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);
            ViewBag.ServerNames = user.Servers.Select(s => s.ServerShortName).ToArray();

            return View(user);
        }
        //
        /// <summary>
        /// GET: /Users/Create
        /// </summary>
        /// <returns>a view containing a list of roles</returns>
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = userViewModel.Email, Email = userViewModel.Email };
                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        //
        // GET: /Users/Edit/1
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);
            string[] _userServers = user.Servers.Select(s => s.ServerShortName).ToArray();

            EditUserViewModel _view = new EditUserViewModel()
            {
                Id = user.Id,
                UserName = user.UserName,
                Email = user.Email,
                FirstName = user.FirstName,
                LastName = user.LastName,
                FullName = user.FullName,
                UserNicName = user.UserNicName,
                PhoneNumber = user.PhoneNumber,

                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                }),
                ServersList = ServerManager.Servers.
                    Where(s => s.CompanyId == user.CompanyId).
                    Select(s => new SelectListItem()
                    {
                        Selected = _userServers.Contains(s.ServerShortName),
                        Text = s.ServerShortName,
                        Value = s.ServerShortName
                    }).ToList()
            };
            foreach (ApplicationServer _s in user.Servers.Where(s => s.CompanyId != user.CompanyId))
                _view.ServersList.Add(new SelectListItem()
                {
                    Selected = true,
                    Text = _s.ServerShortName,
                    Value = _s.ServerShortName
                });
            return View(_view);
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(
            [Bind(Include = "Id,UserName,Email,FullName,FirstName,LastName,UserNicName,PhoneNumber,RolesList,ServersList")] EditUserViewModel editUser,
            params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                bool _confirmEmail = false;
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                //
                if( user.UserName != editUser.UserName )
                    user.UserName = editUser.UserName;
                if( user.Email != editUser.Email )
                {
                    user.Email = editUser.Email;
                    user.EmailConfirmed = false;
                    _confirmEmail = true;
                }
                if ( user.FirstName != editUser.FirstName )
                    user.FirstName = editUser.FirstName;
                if( user.LastName != editUser.LastName )
                    user.LastName = editUser.LastName;
                if( user.FullName != editUser.FullName )
                    user.FullName = editUser.FullName;
                if( user.UserNicName != editUser.UserNicName )
                    user.UserNicName = editUser.UserNicName;
                if( user.PhoneNumber != editUser.PhoneNumber )
                {
                    user.PhoneNumber = editUser.PhoneNumber;
                    user.PhoneNumberConfirmed = false;
                }
                //
                // Add and delete roles
                //
                var userRoles = await UserManager.GetRolesAsync(user.Id);
                selectedRole = selectedRole ?? new string[] { };
                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                // remove roles
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                //
                // Add and delete servers
                //
                List<string> _existingServers = user.Servers.Select( _s => _s.ServerShortName ).ToList();
                foreach ( SelectListItem _item in editUser.ServersList )
                {
                    bool _found = _existingServers.Contains( _item.Value );
                    if ( !_found && _item.Selected )
                        await ServerManager.AddToServerAsync( user, _item.Value );
                    if ( _found && !_item.Selected )
                        await ServerManager.RemoveFromServerAsync( user, _item.Value );
                    if ( !result.Succeeded )
                    {

WebSrv/Views/UsersAdmin/Create.cshtml
@model NSG.Identity.Models.RegisterViewModel
@{
    ViewBag.Title = "Create";
}

<h2>User (Create)</h2>

@using (Html.BeginForm("Create", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="form-actions no-color">
        <div class="nsg-float-left text-left">
            <span>
                @Html.ActionLink("Back to List", "Index")
            </span>
        </div>
        <div class="nsg-float-right text-right">
            <span>
                <input type="submit" value="Create" class="btn btn-info" />
            </span>
        </div>
        <div style="clear: both;"></div>
    </div>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-error" })
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-lg-1 col-md-2 col-sm-12 control-label" })
        <div class="col-lg-1 col-md-1 col-sm-120">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-lg-1 col-md-2 col-sm-12 control-label" })
        <div class="col-lg-1 col-md-1 col-sm-120">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-lg-1 col-md-2 col-sm-12 control-label" })
        <div class="col-lg-1 col-md-1 col-sm-120">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-1 col-md-2 col-sm-12 control-label">
            Select User Role
        </label>
        <div class="col-lg-1 col-md-1 col-sm-120">
            @foreach (var item in (SelectList)ViewBag.RoleId)
            {
                <input type="checkbox" name="SelectedRoles" value="@item.Value" class="checkbox-inline" />
                @Html.Label(item.Value, new { @class = "control-label" })
            }
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebSrv/Views/UsersAdmin/Delete.cshtml
@model NSG.Identity.ApplicationUser

@{
    ViewBag.Title = "Delete";
}

<h2>User (Delete)</h2>
<div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <div class="nsg-float-left text-left">
                <span>
                    @Html.ActionLink("Back to List", "Index")
                </span>
            </div>
            <div class="nsg-float-right text-right">
                <span>
                    <strong>Are you sure you want to delete this User?</strong>
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </span>
            </div>
            <div class="nsg-clear-both"></div>
        </div>
    }
</div>
<hr />
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
    </dl>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>

WebSrv/Views/UsersAdmin/Details.cshtml
@model NSG.Identity.ApplicationUser

@{
    ViewBag.Title = "Details";
}
<h2>User (Details)</h2>
<div>
    <div class="form-actions no-color">
        <div class="nsg-float-left text-left">
            <span>
                @Html.ActionLink("Back to List", "Index")
            </span>
        </div>
        <div class="nsg-float-right text-right">
            <span>
                @Html.ActionLink("Edit", "Edit", new { id = Model.Id })
            </span>
        </div>
        <div class="nsg-clear-both"></div>
    </div>
    <hr />
    <div class="col-lg-6 col-md-6 col-sm-12">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.UserName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.UserName)
            </dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
        </dl>

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FullName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.FullName)
            </dd>
        </dl>

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.UserNicName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.UserNicName)
            </dd>
        </dl>
    </div>

    <div class="col-lg-6 col-md-6 col-sm-12">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.FirstName)
            </dd>
        </dl>

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>
        </dl>

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.PhoneNumber)
            </dd>
        </dl>
        
        <dl class="dl-horizontal">
            &nbsp;
        </dl>
    </div>
</div>
<div class="col-lg-1 col-md-1 col-sm-12">
    <hr />
    @if (ViewBag.RoleNames.Count == 0)
    {
        <p>No roles found for this user.</p>
    }
    <dl class="dl-horizontal">
        <dt>
            Roles
        </dt>
        <dd>
            @foreach (var item in ViewBag.RoleNames)
            {
                <div style="padding:0 18px 8px 0; float: left;">
                    @item
                </div>
            }
        </dd>
    </dl>
    <div style="clear: left;"></div>
    @if (ViewBag.RoleNames.Count == 0)
    {
        <p>No servers found for this user.</p>
    }
    <dl class="dl-horizontal">
        <dt>
            Servers
        </dt>
        <dd>
            @foreach (var item in ViewBag.ServerNames)
            {
                <div style="padding:0 18px 8px 0; float: left;">
                    @item
                </div>
            }
        </dd>
    </dl>
    <div class="nsg-clear-left"></div>
</div>

WebSrv/Views/UsersAdmin/Edit.cshtml
@model NSG.Identity.Models.EditUserViewModel
@{
    ViewBag.Title = "Edit";
}

<h2>User (Edit)</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <div class="form-actions no-color">
        <div class="nsg-float-left text-left">
            <span>
                @Html.ActionLink("Back to List", "Index")
            </span>
        </div>
        <div class="nsg-float-right text-right">
            <span>
                <input type="submit" value="Save" class="btn btn-info" />
            </span>
        </div>
        <div style="clear: both;"></div>
    </div>
    <hr />
    <div class="form-horizontal">
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="form-group">
                @Html.LabelFor(model => model.UserName, new { @class = "control-label col-lg-2 col-md-3 col-sm-12" })
                <div class="col-lg-9 col-md-9 col-sm-12">
                    @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, new { @class = "control-label col-lg-2 col-md-3 col-sm-12" })
                <div class="col-lg-9 col-md-9 col-sm-12">
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FullName, new { @class = "control-label col-lg-2 col-md-3 col-sm-12" })
                <div class="col-lg-9 col-md-9 col-sm-12">
                    @Html.TextBoxFor(m => m.FullName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.FullName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UserNicName, new { @class = "control-label col-lg-2 col-md-3 col-sm-12" })
                <div class="col-lg-9 col-md-9 col-sm-12">
                    @Html.TextBoxFor(m => m.UserNicName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserNicName)
                </div>
            </div>
        </div>

        <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-lg-2 col-md-3 col-sm-12" })
                <div class="col-lg-9 col-md-9 col-sm-12">
                    @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.FirstName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, new { @class = "control-label col-lg-2 col-md-3 col-sm-12" })
                <div class="col-lg-9 col-md-9 col-sm-12">
                    @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.LastName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PhoneNumber, new { @class = "control-label col-lg-2 col-md-3 col-sm-12" })
                <div class="col-lg-9 col-md-9 col-sm-12">
                    @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PhoneNumber)
                </div>
            </div>
        </div>
        <hr />

        <div class="col-lg-1 col-md-1 col-sm-12">
            <div class="form-group row">
                @Html.Label("Roles", new { @class = "control-label col-lg-1 col-md-1 col-sm-12" })
                <div class="col-lg-1 col-md-1 col-sm-120">
                    @foreach (var item in Model.RolesList)
                    {
                        <div style="padding:0 12px 0 0; float: left;">
                            @Html.HiddenFor( m => item.Value)
                            <input type="checkbox" name="SelectedRole" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                            @Html.Label(item.Value, new { @class = "control-label" })
                        </div>
                    }
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Servers", new { @class = "control-label col-lg-1 col-md-1 col-sm-12" })
                <div class="col-lg-1 col-md-1 col-sm-120">
                    @for (int i = 0; i < Model.ServersList.Count(); i++)
                    {
                        SelectListItem item = Model.ServersList[i];
                        <div style="padding:0 12px 0 0; float: left;">
                            @Html.HiddenFor(m => m.ServersList[i].Value)
                            @Html.CheckBoxFor(m => m.ServersList[i].Selected)
                            @Html.LabelFor(m => m.ServersList[i].Selected, Model.ServersList[i].Value)
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
}
<hr />
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebSrv/Views/UsersAdmin/Index.cshtml
@model IEnumerable<NSG.Identity.ApplicationUser>
@{
    ViewBag.Title = "Index";
}
<h2>User Management</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
        </th>
        <th>
            User Name
        </th>
        <th>
            E-mail
        </th>
        <th>
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td style="width: 120px;">
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Edit", "Edit", new { id = item.Id })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @style = "color: red;" })
            </td>
        </tr>
    }

</table>