WebSrv/Models/CompanyEmailTemplate.cs
//
using System;
using System.Collections.Generic;
using System.Web.Mvc;
//
using NSG.Identity.Incidents;
//
namespace WebSrv.Models
{
    public class CompanyEmailTemplate
    {
        public List<SelectListItem> CompanySelect { get; set; }
        public List<SelectListItem> IncidentTypeSelect { get; set; }
        public List<EmailTemplateData> CompanyTemplates { get; set; }
        public string IncidentTypeJson { get; set; } // JSON string of array of IncidentType
        public EmailTemplate Template { get; set; }
    }
}

WebSrv/Controllers/CompanyEmailTemplateController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Data.Entity.Validation;
using Microsoft.AspNet.Identity;
//
using NSG.Identity;
using NSG.Identity.Incidents;
using WebSrv.Models;
//
namespace WebSrv.Controllers
{
    public class CompanyEmailTemplateController : BaseController
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        //
        private bool IsValidCompany(int companyId )
        {
            string _userId = User.Identity.GetUserId();
            if (string.IsNullOrEmpty(_userId)) return false;
            var _companies = db.Users.Where(u => u.Id == _userId).FirstOrDefault()
                .Servers.Select(s => s.Company).GroupBy(c => new { c.CompanyId })
                .Select(d => d.Key.CompanyId ).ToArray();
            int _index = Array.FindIndex<int>(_companies, x => x == companyId );
            return ( _index < 0 ? false : true );
        }
        //
        private SelectListItem[] GetUsersCompanies( string userId )
        {
            if (string.IsNullOrEmpty(userId))
                return new SelectListItem[0];
            return db.Users.Where(u => u.Id == userId).FirstOrDefault()
                .Servers.Select(s => s.Company).GroupBy(c => new { c.CompanyId, c.CompanyName })
                .Select(d => new SelectListItem() { Value = d.Key.CompanyId.ToString(), Text = d.Key.CompanyName })
                .ToArray();
        }
        // GET: CompanyEmailTemplate
        public ActionResult Index(int? companyId)
        {
            // SelectListItem
            EmailTemplateAccess _access = new EmailTemplateAccess(db);
            string _userId = User.Identity.GetUserId();
            int _companyId = 0;
            var _companies = GetUsersCompanies(_userId);
            if( _companies != null && _companies.Length > 0 )
            {
                int _index = 0;
                if(companyId.HasValue )
                {
                    _index = Array.FindIndex<SelectListItem>(_companies, x => x.Value == companyId.Value.ToString());
                    if (_index < 0)
                        _index = 0;
                }
                _companyId = Convert.ToInt32( _companies[_index].Value );
                _companies[_index].Selected = true;
            }
            CompanyEmailTemplate _viewModel = new CompanyEmailTemplate()
            {
                CompanySelect = _companies.ToList(),
                CompanyTemplates = _access.ListByCompany( _companyId )
            };
            var emailTemplates = db.EmailTemplates.Include(e => e.Company).Include(e => e.IncidentType);
            return View( _viewModel );
        }
        //
        /// <summary>
        /// GET: CompanyEmailTemplate/Details/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int? companyId, int? incidentTypeId)
        {
            if ( !companyId.HasValue || !incidentTypeId.HasValue )
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if( !IsValidCompany( companyId.Value ) )
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }
            EmailTemplateAccess _access = new EmailTemplateAccess(db);
            EmailTemplateData _row = _access.GetByPrimaryKey(companyId.Value, incidentTypeId.Value);
            if (_row == null)
            {
                return HttpNotFound();
            }
            return View(_row);
        }
        //
        /// <summary>
        /// GET: CompanyEmailTemplate/Create/?companyId=1
        /// </summary>
        /// <param name="companyId"></param>
        /// <returns></returns>
        public ActionResult Create( int? companyId )
        {
            return View(CreateCreateViewModel(new EmailTemplate()) );
        }
        //
        CompanyEmailTemplate CreateCreateViewModel(EmailTemplate template)
        {
            string _userId = User.Identity.GetUserId();
            List<SelectListItem> _companies = GetUsersCompanies(_userId).ToList();
            var _sli = new List<SelectListItem>() {
                new SelectListItem() { Value = "", Text = "- Select a incident type- " }
            }.Union(new SelectList(db.IncidentTypes, "IncidentTypeId", "IncidentTypeShortDesc")).ToList();
            foreach (EmailTemplate _et in db.EmailTemplates)
            {
                _sli.Remove(_sli.Find(it => it.Value == _et.IncidentTypeId.ToString()));
            }
            JavaScriptSerializer _js_slzr = new JavaScriptSerializer();
            IncidentTypeAccess _access = new IncidentTypeAccess(db);
            string _itJsonString = _js_slzr.Serialize(_access.List());
            //
            // ViewBag.CompanyId = _companies;
            // ViewBag.IncidentTypeId = _sli;
            // ViewBag.IncidentType = _itJsonString;
            CompanyEmailTemplate _viewModel = new CompanyEmailTemplate()
            {
                CompanySelect = _companies,
                // List<EmailTemplateData> CompanyTemplates;
                IncidentTypeSelect = _sli,
                IncidentTypeJson = _itJsonString, // JSON string of array of IncidentType
                Template = template
            };
            return _viewModel;
        }
        //
        // POST: CompanyEmailTemplate/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CompanyEmailTemplate companyEmailTemplate)
        {
            try
            {
                if (companyEmailTemplate != null)
                {
                    if (companyEmailTemplate.Template != null)
                    {
                        db.EmailTemplates.Add(companyEmailTemplate.Template);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        Error("Company Email Template: empty."); // in BaseController
                    }
                }
                else
                {
                    Error("Company Email Template: empty view model."); // in BaseController
                }
            }
            catch (DbEntityValidationException _entityEx)
            {
                Base_AddErrors(_entityEx);
            }
            catch (Exception _ex)
            {
                Base_AddErrors(_ex);
            }
            return View(CreateCreateViewModel(companyEmailTemplate.Template));
        }
        //
        // GET: CompanyEmailTemplate/Edit/5
        public ActionResult Edit(int? companyId, int? incidentTypeId)
        {
            if (!companyId.HasValue || !incidentTypeId.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (!IsValidCompany(companyId.Value))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }
            EmailTemplateAccess _access = new EmailTemplateAccess(db);
            EmailTemplateData _row = _access.GetByPrimaryKey(companyId.Value, incidentTypeId.Value);
            if (_row == null)
            {
                return HttpNotFound();
            }
            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "CompanyShortName", _row.CompanyId);
            ViewBag.IncidentTypeId = new SelectList(db.IncidentTypes, "IncidentTypeId", "IncidentTypeShortDesc", _row.IncidentTypeId);
            return View(_row);
        }

        // POST: CompanyEmailTemplate/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CompanyId,IncidentTypeId,SubjectLine,EmailBody,TimeTemplate,ThanksTemplate,LogTemplate,Template,FromServer")] EmailTemplate emailTemplate)
        {
            if (ModelState.IsValid)
            {
                if (!IsValidCompany(emailTemplate.CompanyId))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
                }
                db.Entry(emailTemplate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            EmailTemplateAccess _access = new EmailTemplateAccess(db);
            EmailTemplateData _row = _access.GetByPrimaryKey(emailTemplate.CompanyId, emailTemplate.IncidentTypeId);
            if (_row == null)
            {
                return HttpNotFound();
            }
            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "CompanyShortName", emailTemplate.CompanyId);
            ViewBag.IncidentTypeId = new SelectList(db.IncidentTypes, "IncidentTypeId", "IncidentTypeShortDesc", emailTemplate.IncidentTypeId);
            return View(_row);
        }
        //
        /// <summary>
        /// GET: CompanyEmailTemplate/Delete/?companyId=1&incidentTypeId=1026
        /// </summary>
        /// <param name="companyId"></param>
        /// <param name="incidentTypeId"></param>
        /// <returns></returns>
        public ActionResult Delete(int? companyId, int? incidentTypeId)
        {
            if (!companyId.HasValue || !incidentTypeId.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (!IsValidCompany(companyId.Value))
            {

WebSrv/Views/CompanyEmailTemplate/CompanyEmailTemplateDetailsPartial.cshtml
@using WebSrv.Models;
@model EmailTemplateData
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Company Short Name
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CompanyShortName)
        </dd>

        <dt>
            Incident Type
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IncidentTypeShortDesc)
        </dd>

        <dt>
            Use Server Values
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FromServer)
        </dd>

        <dt>
            Subject Line
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SubjectLine)
        </dd>

        <dt>
            Body Template
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EmailBody)
        </dd>

        <dt>
            Time Template
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TimeTemplate)
        </dd>

        <dt>
            Thanks Template
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ThanksTemplate)
        </dd>

        <dt>
            Log Template
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LogTemplate)
        </dd>

        <dt>
            Template
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Template)
        </dd>

    </dl>
</div>

WebSrv/Views/CompanyEmailTemplate/Create.cshtml
@using WebSrv.Models;
@using NSG.Identity.Incidents;
@model CompanyEmailTemplate
@{
    ViewBag.Title = "Create";
}
<h2>Company E-Mail Template (Create)</h2>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-actions no-color">
        <div class="nsg-float-left text-left">
            <span>
                @Html.ActionLink("Back to List", "Index", "CompanyEmailTemplate", new { id = "backLink" })
            </span>
        </div>
        <div class="nsg-float-right text-right">
            <span>
                <input type="submit" value="Create" class="btn btn-info" />
            </span>
        </div>
        <div style="clear: both;"></div>
    </div>
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="panel-help">
                <div class="panel-title">
                    <a class="collapsed accordion-toggle" role="button" data-toggle="collapse"
                       data-parent="#accordion"
                       href="#collapse-help"
                       aria-expanded="false" aria-controls="collapse-help">
                        <div class="nsg-bold col-lg-1 col-md-1 col-sm-12">
                            E-Mail Template Variable List
                        </div>
                        <div class="nsg-clear-left"></div>
                    </a>
                </div>
            </div>
            <div id="collapse-help" class="panel-collapse collapse" role="tabpanel" aria-labelledby="panel-help">
                <div class="panel-body">
                    @Html.Partial("../Shared/EmailTemplateHelpPartial")
                </div>
            </div>
        </div>
    </div>
    <div class="form-horizontal">

        @Html.HiddenFor(model => model.CompanySelect)
        @Html.HiddenFor(model => model.CompanyTemplates)
        @Html.HiddenFor(model => model.IncidentTypeSelect)
        <!--
        Html.HiddenFor(model => model.IncidentTypeJson)
        -->

        <div class="form-group">
            <label for='Template_CompanyId' class='control-label col-lg-1 col-md-2 col-sm-12'>Company</label>
            <div class="col-lg-1 col-md-1 col-sm-120">
                @Html.DropDownListFor(model => model.Template.CompanyId, Model.CompanySelect, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Template.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for='Template_IncidentTypeId' class='control-label col-lg-1 col-md-2 col-sm-12'>Incident Type</label>
            <div class="col-lg-1 col-md-1 col-sm-120">
                @Html.DropDownListFor(model => model.Template.IncidentTypeId, Model.IncidentTypeSelect, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Template.IncidentTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for='Template_FromServer' class='control-label col-lg-1 col-md-2 col-sm-12'>Use Server Values</label>
            <div class="col-lg-1 col-md-1 col-sm-120">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Template.FromServer)
                    @Html.ValidationMessageFor(model => model.Template.FromServer, "", new { @class = "text-danger" })
                    <strong>&lt;= From e-mail name and address</strong>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label for='Template_SubjectLine' class='control-label col-lg-1 col-md-2 col-sm-12'>Subject Line</label>
            <div class="col-lg-1 col-md-1 col-sm-120">
                @Html.EditorFor(model => model.Template.SubjectLine, new { htmlAttributes = new { @class = "form-control", @style = "max-width:680px" } })
                @Html.ValidationMessageFor(model => model.Template.SubjectLine, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for='Template_EmailBody' class='control-label col-lg-1 col-md-2 col-sm-12'>Email Template</label>
            <div class="col-lg-1 col-md-1 col-sm-120">
                @Html.TextAreaFor(model => model.Template.EmailBody, new { @class = "form-control", @rows = "3", @style = "max-width:680px" })
                @Html.ValidationMessageFor(model => model.Template.EmailBody, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for='Template_TimeTemplate' class='control-label col-lg-1 col-md-2 col-sm-12'>Time Template</label>
            <div class="col-lg-1 col-md-1 col-sm-120">
                @Html.EditorFor(model => model.Template.TimeTemplate, new { htmlAttributes = new { @class = "form-control", @style = "max-width:680px" } })
                @Html.ValidationMessageFor(model => model.Template.TimeTemplate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for='Template_ThanksTemplate' class='control-label col-lg-1 col-md-2 col-sm-12'>ThanksTemplate</label>
            <div class="col-lg-1 col-md-1 col-sm-120">
                @Html.EditorFor(model => model.Template.ThanksTemplate, new { htmlAttributes = new { @class = "form-control", @style = "max-width:680px" } })
                @Html.ValidationMessageFor(model => model.Template.ThanksTemplate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for='Template_LogTemplate' class='control-label col-lg-1 col-md-2 col-sm-12'>Log Template</label>
            <div class="col-lg-1 col-md-1 col-sm-120">
                @Html.EditorFor(model => model.Template.LogTemplate, new { htmlAttributes = new { @class = "form-control", @style = "max-width:680px" } })
                @Html.ValidationMessageFor(model => model.Template.LogTemplate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for='Template_Template' class='control-label col-lg-1 col-md-2 col-sm-12'>Template</label>
            <div class="col-lg-1 col-md-1 col-sm-120">
                @Html.EditorFor(model => model.Template.Template, new { htmlAttributes = new { @class = "form-control", @style = "max-width:680px" } })
                @Html.ValidationMessageFor(model => model.Template.Template, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}
@Scripts.Render("~/bundles/jquery")
<script type="text/javascript">
    //
    var codeName = 'CompanyEmailTemplate.Create';
    //
    $(document).ready(function () {
        $("#Template_IncidentTypeId").change(function () {
            console.log(codeName + ': in IncidentTypeId change.');
            var this_ = $(this);
            var id = parseInt( this_.val( ) );
            var incidentType = $.parseJSON( @Html.Raw(Json.Encode(@Model.IncidentTypeJson)) );
            console.log( incidentType );
            var it = incidentType.find(function (el) { return el.IncidentTypeId === id; });
            if (it !== null && it !== undefined) {
                console.log(it);
                // assign the values from the default to the company specific e-mail template
                $('#Template_FromServer').attr('checked', it.IncidentTypeFromServer);
                $('#Template_SubjectLine').val(it.IncidentTypeSubjectLine);
                $('#Template_EmailBody').val(it.IncidentTypeEmailTemplate);
                $('#Template_TimeTemplate').val(it.IncidentTypeTimeTemplate);
                $('#Template_ThanksTemplate').val(it.IncidentTypeThanksTemplate);
                $('#Template_LogTemplate').val(it.IncidentTypeLogTemplate);
                $('#Template_Template').val(it.IncidentTypeTemplate);
            } else {
                console.error(codeName + ': ERROR, IncidentType not found.');
            }
        });
        //
        $('#backLink').click(function () {
            var this_ = $(this);
            var id = $('#CompanyId').val();
            this_[0].search = `?companyId=${id}`;
            console.log(codeName + ' backLink clicked, ' + this_[0].search);
        });
    });
    //
</script>

WebSrv/Views/CompanyEmailTemplate/Delete.cshtml
@using WebSrv.Models;
@model EmailTemplateData
@{
    ViewBag.Title = "Delete";
}
<h2>Company E-Mail Template (Delete)</h2>
<div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <div class="nsg-float-left text-left">
                <span>
                    @Html.ActionLink("Back to List", "Index", new { companyId = Model.CompanyId })
                </span>
            </div>
            <div class="nsg-float-right text-right">
                <span>
                    <strong>Are you sure you want to delete this?</strong>
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </span>
            </div>
            <div class="nsg-clear-both"></div>
        </div>
    }
</div>
@Html.Partial("./CompanyEmailTemplateDetailsPartial", Model)

WebSrv/Views/CompanyEmailTemplate/Details.cshtml
@using WebSrv.Models;
@model EmailTemplateData
@{
    ViewBag.Title = "Details";
}

<h2>Company E-Mail Template (Details)</h2>

<div class="form-actions no-color">
    <div class="nsg-float-left text-left">
        <span>
            @Html.ActionLink("Back to List", "Index", new { companyId = Model.CompanyId })
        </span>
    </div>
    <div class="nsg-float-right text-right">
        <span>
            @Html.ActionLink("Edit", "Edit", new { companyId = Model.CompanyId, incidentTypeId = Model.IncidentTypeId })
        </span>
    </div>
    <div class="nsg-clear-both"></div>
</div>
@Html.Partial("./CompanyEmailTemplateDetailsPartial", Model)

WebSrv/Views/CompanyEmailTemplate/Edit.cshtml
@using WebSrv.Models;
@model EmailTemplateData
@{
    ViewBag.Title = "Edit";
}

<h2>Company E-Mail Template (Edit)</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-actions no-color">
        <div class="nsg-float-left text-left">
            <span>
                @Html.ActionLink("Back to List", "Index", new { companyId = Model.CompanyId })
            </span>
        </div>
        <div class="nsg-float-right text-right">
            <span>
                <input type="submit" value="Save" class="btn btn-info" />
            </span>
        </div>
        <div style="clear: both;"></div>
    </div>
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="panel-help">
                <div class="panel-title">
                    <a class="collapsed accordion-toggle" role="button" data-toggle="collapse"
                       data-parent="#accordion"
                       href="#collapse-help"
                       aria-expanded="false" aria-controls="collapse-help">
                        <div class="nsg-bold col-lg-1 col-md-1 col-sm-12">
                            E-Mail Template Variable List
                        </div>
                        <div class="nsg-clear-left"></div>
                    </a>
                </div>
            </div>
            <div id="collapse-help" class="panel-collapse collapse" role="tabpanel" aria-labelledby="panel-help">
                <div class="panel-body">
                    @Html.Partial("../Shared/EmailTemplateHelpPartial")
                </div>
            </div>
        </div>
    </div>
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.CompanyId)
        @Html.HiddenFor(model => model.IncidentTypeId)

        <div class="form-group">
            <label for='CompanyShortName' class='control-label col-lg-1 col-md-2 col-sm-12'>Company</label>
            <div class="col-lg-1 col-md-2 col-sm-12" style='padding-top: .6em;'>
                @Html.DisplayFor(model => model.CompanyShortName)
            </div>
            <div class="col-lg-8 col-md-8 col-sm-12">
                <label for='IncidentTypeShortDesc' class='control-label'>Incident Type &nbsp; </label>
                @Html.DisplayFor(model => model.IncidentTypeShortDesc)
            </div>
        </div>

        <div class="form-group">
            <label for='FromServer' class='control-label col-lg-1 col-md-2 col-sm-12'>Use Server Values</label>
            <div class="col-lg-1 col-md-1 col-sm-120">
                <div class="checkbox">
                    @Html.EditorFor(model => model.FromServer)
                    @Html.ValidationMessageFor(model => model.FromServer, "", new { @class = "text-danger" })
                    <strong>&lt;= From e-mail name and address</strong>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label for='SubjectLine' class='control-label col-lg-1 col-md-2 col-sm-12'>Subject Line</label>
            <div class="col-lg-1 col-md-1 col-sm-120">
                @Html.EditorFor(model => model.SubjectLine, new { htmlAttributes = new { @class = "form-control", @style = "max-width:680px" } })
                @Html.ValidationMessageFor(model => model.SubjectLine, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for='EmailBody' class='control-label col-lg-1 col-md-2 col-sm-12'>Email Template</label>
            <div class="col-lg-1 col-md-1 col-sm-120">
                @Html.TextAreaFor(model => model.EmailBody, new { @class = "form-control", @rows = "3", @style = "max-width:680px" })
                @Html.ValidationMessageFor(model => model.EmailBody, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for='TimeTemplate' class='control-label col-lg-1 col-md-2 col-sm-12'>Time Template</label>
            <div class="col-lg-1 col-md-1 col-sm-120">
                @Html.EditorFor(model => model.TimeTemplate, new { htmlAttributes = new { @class = "form-control", @style = "max-width:680px" } })
                @Html.ValidationMessageFor(model => model.TimeTemplate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for='ThanksTemplate' class='control-label col-lg-1 col-md-2 col-sm-12'>ThanksTemplate</label>
            <div class="col-lg-1 col-md-1 col-sm-120">
                @Html.EditorFor(model => model.ThanksTemplate, new { htmlAttributes = new { @class = "form-control", @style = "max-width:680px" } })
                @Html.ValidationMessageFor(model => model.ThanksTemplate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for='LogTemplate' class='control-label col-lg-1 col-md-2 col-sm-12'>Log Template</label>
            <div class="col-lg-1 col-md-1 col-sm-120">
                @Html.EditorFor(model => model.LogTemplate, new { htmlAttributes = new { @class = "form-control", @style = "max-width:680px" } })
                @Html.ValidationMessageFor(model => model.LogTemplate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for='Template' class='control-label col-lg-1 col-md-2 col-sm-12'>Template</label>
            <div class="col-lg-1 col-md-1 col-sm-120">
                @Html.EditorFor(model => model.Template, new { htmlAttributes = new { @class = "form-control", @style = "max-width:680px" } })
                @Html.ValidationMessageFor(model => model.Template, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}

WebSrv/Views/CompanyEmailTemplate/Index.cshtml
@using WebSrv.Models;
@model CompanyEmailTemplate
@{
    ViewBag.Title = "Index";
    int companyId = 0;
    if (Model.CompanyTemplates.Count > 0)
    {
        companyId = Model.CompanyTemplates[0].CompanyId;
    }
}
<h2>Company E-Mail Template (List)</h2>
<p>
    @Html.ActionLink("Create New", "Create", "CompanyEmailTemplate", new { id = "createLink" })
</p>
<div data-submit-url="@Url.Action("Index", "CompanyEmailTemplate")">
    <label for='Company'>Company</label>
    @Html.DropDownList("CompanyDropDown", Model.CompanySelect)
</div>
<table class="table">
    <tr>
        <th style="width: 100px;"></th>
        <th style="width: 90px;">
            Short Desc
        </th>
        <th style="width: 100px;">
            Use Server Values
        </th>
        <th>
            Subject Line
        </th>
        <th>
            Body
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.CompanyTemplates) {
    <tr>
        <td>
            @Html.ActionLink("Details", "Details", new { companyId = item.CompanyId, incidentTypeId = item.IncidentTypeId } ) |
            @Html.ActionLink("Edit", "Edit", new { companyId = item.CompanyId, incidentTypeId = item.IncidentTypeId })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IncidentTypeShortDesc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FromServer)
        </td>
        <td>
            @( item.SubjectLine.TruncateString(35) )
        </td>
        <td>
            @( item.EmailBody.TruncateString(35) )
        </td>
        <td>
            @Html.ActionLink("Delete", "Delete", new { companyId = item.CompanyId, incidentTypeId = item.IncidentTypeId })
        </td>
    </tr>
}
</table>
@Scripts.Render("~/bundles/jquery")
<script type="text/javascript">
    //
    $(document).ready(function () {
        //
        $("#CompanyDropDown").change(function () {
            var this_ = $(this);
            var id = this_.val();
            console.log( `#CompanyDropDown changed... ${id}` );
            var url = this_.parent().data("submit-url") + `?companyId=${id}`;
            window.location.href = url;
        });
        //
        $('#createLink').click(function () {
            var this_ = $(this);
            var id = $('#CompanyDropDown').val();
            this_[0].search = `?companyId=${id}`;
            console.log(this_[0].search);
        });
    });
    //
</script>